graph TD
    Client[Client / Postman] -->|POST /api/orders| CommandService(Command Service :8080)
    Client -->|GET /api/analytics/...| QueryService(Query Service :8081)
    
    subgraph Write Side
        CommandService -->|Insert Order & Outbox Event| WriteDB[(Primary PostgreSQL)]
        CommandService -->|Poll Outbox & Publish| RabbitMQ[RabbitMQ Message Broker]
    end
    
    subgraph Read Side
        RabbitMQ -->|Consume Event| ConsumerService(Consumer Service)
        ConsumerService -->|Update Materialized Views| ReadDB[(Read PostgreSQL)]
        QueryService -->|Query Materialized Views| ReadDB
    end
